version: '3.4'

services:
  audio-fe:
    ports:
      - 8080:80
    build: audio-fe/
    environment:
      - AUDIO_BE_URI=audio-be:5000
    depends_on:
      - audio-be
  audio-be:
    ports:
      - 5000:5000
    build: audio-be/
    runtime: nvidia